maximum_name_length: 20
maximum_email_length: 50
minimum_password_length: 6
image_size: 50
image_size100: 100
image_size_edit: 200
image_resize: 400
image_storage: 5
remember: 1
image_type:
  - jpg
  - jpeg
  - gif
  - png
per_page: 10  
image_type_accept: image/jpeg,image/gif,image/png
maximum_name_category_length: 200
maximum_alphabet_length: 20
filter:
  all: "get_all"
  learned: "learned"
  not_learned: "not_learned"
